[package]
name = "pulsear-cli"
version = "0.1.0"
edition = "2021"
authors = ["Lemonorn <mmagicode@gmail.com>"]
description = """
A rust terminal client of a NAS system
"""
license = "MIT"
readme = "../README.md"
repository = "https://github.com/linepi/pulsear"

[dependencies]
tui = "0.19.0"
